#pragma once

#include <stdexcept>
#include <array>
#include <cassert>
#include <chrono>
#include <iostream>
#include <numeric>
#include <string>
#include <vector>
#include <fstream>
#include <sstream>
#include <set>
#include <unordered_set>
#include <cstdlib>
#include <cstring>
#include <limits>
#include <memory>
#include <unordered_map>
#include <atomic>
#include <algorithm>
#include <random>
#include <map>
#include <deque>
